services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: inserir_usuario_mysql
      WORDPRESS_DB_PASSWORD: ${SENHA_DB}
      WORDPRESS_DB_NAME: inserir_nome_banco_de_dados
    volumes:
      - /wordpress/data:/var/www/html